# shared configmap
kind: ConfigMap
apiVersion: v1
metadata:
  name: shared-configmap
  labels:
    spring.cloud.kubernetes.config: "true"
  annotations:
    spring.cloud.kubernetes.configmap.apps: "first-config-server, second-config-server"
data:
  app.user.name: Inna
