# service-specific configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: first-config-server
  labels:
    spring.cloud.kubernetes.config: "true"
data:
  app.lang: en
---
# NodePort to send a request to the service
kind: Service
apiVersion: v1
metadata:
  name: first-server-app-service
spec:
  type: NodePort
  selector:
    app: first-server-app
  ports:
    - nodePort: 30163
      port: 8080
      targetPort: 8080

---
# internal service for watcher
apiVersion: v1
kind: Service
metadata:
  labels:
    app: first-server-app
  name: first-config-server
  annotations:
    boot.spring.io/actuator: http://:8080/actuator
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: first-server-app
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-server-app-deployment
  labels:
    app: first-server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-server-app
  template:
    metadata:
      labels:
        app: first-server-app
    spec:
      containers:
        - name: first-server-app
          image: server-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_APPLICATION_NAME
              value: "first-config-server"
