# shared secret
apiVersion: v1
kind: Secret
metadata:
  name: shared-secret
  labels:
    spring.cloud.kubernetes.config: "true"
  annotations:
    spring.cloud.kubernetes.configmap.apps: "first-config-server, second-config-server"
type: Opaque
data:
  app.user.password: cGFzc3dvcmQ=
